# Generated by Django 5.1.4 on 2025-05-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('月', '月'), ('星', '星'), ('雪', '雪'), ('虹', '虹'), ('その他', 'その他')], max_length=10, verbose_name='クラス')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('status', models.CharField(choices=[('出席', '出席'), ('欠席', '欠席')], max_length=10, verbose_name='出欠')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
